data11 <- read.table("assignment 1.txt", header = TRUE, sep = ";", na.strings = "?")
data <- rbind(data11[data11$Date == "1/2/2007", ], data11[data11$Date == "2/2/2007", ])
data$DateTime <- strptime(paste(data$Date, data$Time, sep = ""), "%d/%m/%Y %H:%M")
png("plot3.png", width=480, height=480)
plot(data$DateTime, data$Sub_metering_1, ylab = "Energy Sub Metering", type = "l")
lines(data$DateTime, data$Sub_metering_2, col = "red")
lines(data$DateTime, data$Sub_metering_3, col = "blue")
legend("topright", lwd = "3", col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
